:construction_worker: Setup GitHub Actions CI with codspeed benchmarking (#2)
* :construction_worker: Setup GitHub Actions Continuous Integration

Running tests on Ubuntu-24.04 and Rust 1.85.0 and current stable (1.91.0).

* :construction: Add placeholder rust file

So that `cargo build` works

* :construction_worker: Add codspeed benchmark GitHub Actions CI workflow

Based on https://codspeed.io/docs/integrations/ci/github-actions#sample-configurations.

* :green_heart: Apt install libgdal-dev

See if this fixes `wrapper.h:5:10: fatal error: 'cpl_atomic_ops.h' file not found`.

* :green_heart: Add criterion_benchmark func to benches/read_geotiff.rs

Can't be too empty. Also renamed ci.yml to bench.yml and explicitly set mode: instrumentation on CodSpeedHQ/action.